// web/src/components/Sidebar.tsx
import React from 'react';
import { useHistory } from 'react-router-dom';
import { FiArrowLeft } from 'react-icons/fi';

import mapMarkerImg from '../assets/images/map-marker.svg';
import '../assets/styles/components/sidebar.css';

const Sidebar: React.FC = () => {
  const { goBack } = useHistory();

  return (
    <aside className="app-sidebar">
      <img src={mapMarkerImg} alt="Happy" />

      <footer>
        <button type="button" onClick={goBack}>
          <FiArrowLeft size={24} color="#FFF" />
        </button>
      </footer>
    </aside>
  );
};

export default Sidebar;

// web/vue/src/components/Sidebar.vue
<template>
  <aside class="app-sidebar">
    <img src="/map-marker.svg" alt="Logo" />

    <footer>
      <button @click="goBack" type="button">
        <arrow-left-icon size="24" color="#fff" />
      </button>
    </footer>
  </aside>
</template>

<script lang="ts">
import Component from 'vue-class-component';
import Vue from 'vue';
import { ArrowLeftIcon } from 'vue-feather-icons';

@Component({
  name: 'sidebar',
  components: {
    ArrowLeftIcon,
  },
})
export default class Sidebar extends Vue {
  goBack() {
    this.$router.go(-1);
  }
}
</script>

<style>
aside.app-sidebar {
  position: fixed;
  height: 100%;
  padding: 32px 24px;
  background: linear-gradient(329.54deg, #15b6d6 0%, #15d6d6 100%);

  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
}

aside.app-sidebar img {
  width: 48px;
}

aside.app-sidebar footer a,
aside.app-sidebar footer button {
  width: 48px;
  height: 48px;

  border: 0;

  background: #12afcb;
  border-radius: 16px;

  cursor: pointer;

  transition: background-color 0.2s;

  display: flex;
  justify-content: center;
  align-items: center;
}

aside.app-sidebar footer a:hover,
aside.app-sidebar footer button:hover {
  background: #17d6eb;
}
</style>
